### ISSUE TITLE
cas-offinder-bulge

### ISSUE THREAD

**Issue by lucapinello** [snugel/cas-offinder#13]
Hi Thanks for the excellent software!

I am trying to run a simple analysis to find all the sequences with 6 mismatches and 1nt bulge either DNA or RNA.

This is my input file:

/data/genomes/hg19.2bit
NNNNNNNNNNNNNNNNNNNNNNN 1 1
GAGTCCGAGCAGAAGAAGAAGGG 6

This is the command I run:
cas-offinder-bulge input_file.txt G output_file.txt

In the output file I see the RNA bulges but not DNA.  

Is this a known bug?

**Comment by spaulraj** [comment]
Hello lucapinello,

Were you able to fix this bug? I am trying to do the same but no I do not see DNA bulges as well.

**Comment by lucapinello** [comment]
Unfortunately no, sorry.

**Comment by pjb7687** [comment]
Hi all,

My colleage Gue-Ho uploaded updated cas-offinder-bulge here:
https://github.com/hyugel/cas-offinder-bulge
