### ISSUE TITLE
cas-offinder-bulge targe sequence change

### ISSUE THREAD

**Issue by Viscacha22** [snugel/cas-offinder#16]
Hi,

I ran cas-offinder-bulge and noticed that the target sequences in my output .txt file are different from my input sequences. Specifically, the first base of the target sequence is gone, and there is an "N" inserted at the end of the sequence, right before the PAM sequence. The issue is present for both RNA and DNA bulges.

input:
./Cas-OFFinder/chromosomes
NNNNNNNNNNNNNNNNNNNNNRG 1 1
CTAACAGTTGCTTTTATCACNGG 3

output (crRNA):
TAACAGTTGCTTTTATCACNNRG

I don't have this problem when I run the original cas-offinder. 
I've also submitted this issue in cas-offinder-bulge. https://github.com/hyugel/cas-offinder-bulge/issues/1

Thanks!

**Comment by pjb7687** [comment]
Seems like it is solved.
