### ISSUE TITLE
Missing off-targets

### ISSUE THREAD

**Issue by joegeorgeson** [snugel/cas-offinder#18]
I have encountered several instances where cas-offinder misses an off-target. I get the same result with macOS 10.13 and Ubuntu 18.04. I show one such example below. Can you please advise if I'm doing something wrong with my input file or something else? Using version Cas-OFFinder v2.4 (Jul  1 2018)

My source of hg19;
wget http://hgdownload.soe.ucsc.edu/goldenPath/hg19/bigZips/chromFa.tar.gz

Here is my input file;
/var/chromosome/human_hg19
NNNNNNNNNNNNNNNNNNNNNNNN
GCTCGGGCTGTTTGCTGTTGGCTG 1

and output file;
GCTCGGGCTGTTTGCTGTTGGCTG	chr2	191829773	GCTCGGGCTGTTTGCTGTTGGCTG	+	0

However, BLAT and other off-target software will find an off-target in chr7 (BLAT output shown below);
browser details YourSeq    24     1    24    24   100.0%  chr2   +   191829774 191829797     24
browser details YourSeq    20     1    22    24    95.5%  chr7   +   128327881 128327902     22

**Comment by pjb7687** [comment]
Hi @joegeorgeson,

It looks like the one in chr7 is a partial match without the last 2 bases:

![match_chr7](https://user-images.githubusercontent.com/1440536/53686450-6a6c1d80-3d27-11e9-9b9c-8634027173d0.png)

Therefore the off-target is has 3 mismatches. Please see the below Cas-OFFinder result with mismatch 3:

GCTCGGGCTGTTTGCTGTTGGCTG        chr7    128327880       GCTCtGGCTGTTTGCTGTTGGCaa        +       3
GCTCGGGCTGTTTGCTGTTGGCTG        chr5    115695271       GCTCtGGgTGTTTGCTGTTGGCaG        +       3
GCTCGGGCTGTTTGCTGTTGGCTG        chr2    61079824        GCTCaGGCTGTTTcCTGTTGGCTc        -       3
GCTCGGGCTGTTTGCTGTTGGCTG        chr2    191829773       GCTCGGGCTGTTTGCTGTTGGCTG        +       0
GCTCGGGCTGTTTGCTGTTGGCTG        chrX    36554232        GCaCtGGCTGTTTGCTGTTtGCTG        -       3

Best,
Jeongbin
