### ISSUE TITLE
Segmentation fault in GPU mode on Mac 

### ISSUE THREAD

**Issue by harijay** [snugel/cas-offinder#2]
Hi 
Thank you for this excellent application. I was able to get it to work on Linux without a problem on CPU and GPU. 
However when I tried using your supplied binary and a self-compiled binary on Mac OSX 10.9.2 (64 bit) with a Iris 1024 OpenCL supported GPU, the program gives a "Segmentation fault"  as soon as it starts. On the Mac,  the CPU mode works fine but takes a while.

Here is what the debugger says :

Haris-MacBook-Pro:~ hari$ ./cas-offinder_mac testinput.txt G cas_gpu_official
Segmentation fault: 11

The debugger outputs:

(lldb) run
Process 7356 launched: './cas-offinder_mac' (x86_64)
Process 7356 stopped
- thread #1: tid = 0x5a2a6, 0x00001234003c3d79 AppleIntelHD5000GraphicsGLDriver`gldBuildComputeProgram + 84, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0xc)
  frame #0: 0x00001234003c3d79 AppleIntelHD5000GraphicsGLDriver`gldBuildComputeProgram + 84
  AppleIntelHD5000GraphicsGLDriver`gldBuildComputeProgram + 84:
  -> 0x1234003c3d79:  movl   0xc(%rdi), %eax
  0x1234003c3d7c:  leaq   0x18(%rax,%rdi), %rax
  0x1234003c3d81:  movq   0x8(%rbx), %rcx
  0x1234003c3d85:  movq   %rax, 0x28(%rcx)

I also compiled my own binary from source and that too segmentation faults on the same Macbook
Apples web page suggest that OpenCl  MacBook Pro (Retina, 13-inch, Late 2013)
Intel Iris Graphics support OpenCL 1.2. I was also able to run Apples demo OpenCL application on the same hardware.

Any ideas on how to get GPU mode working on Mac.
Thanks
Hari

**Comment by pjb7687** [comment]
On behalf of Sangsu Bae,

Any AMD GPU better than 7870 would be okay. Currently we are using AMD R9 290X and it works great.


Jeongbin
