### ISSUE TITLE
please tag updates

### ISSUE THREAD

**Issue by fizwit** [snugel/cas-offinder#25]
For the purposes of reproducible science could you please tag your project. I would also recommend using a 3 or 4 digit semantic versioning scheme; Magor.Minor.Patch.  Please do not follow the git examples by putting a "v" as the leading character. Github will create a "release" once you push a tag.

git tag 2.4.0
git push origin 2.4.0

**Comment by pjb7687** [comment]
Thank you for nice suggestion, to be honest I didn't aware of that feature in 2016. I will add the tag from the next release.

**Comment by dpryan79** [comment]
@pjb7687 Might now be a convenient time to tag a 2.4.1 release, since there have seemingly been a few bug fixes since the last release in 2016?

**Comment by pjb7687** [comment]
Just released v2.4.1.
I am sorry to say that I had to include the prefix 'v' to trigger GA workflow.

**Comment by pjb7687** [comment]
Found a workaround. Removed prefix 'v'!
