### ISSUE TITLE
conda-installed cas-offinder doesn't find GPU

### ISSUE THREAD

**Issue by JoeEmendo** [snugel/cas-offinder#26]
cas-offinder installed via conda running on AWS p3.2xlarge instance can't "see" the GPUs (when running with arg "G" doesn't work and receive error "No OpenCL devices found", but arg "C" works fine).
When installed from source not in a conda environment it works fine with arg "G". It could be an issue of opencl, or of conda, but I wanted to let you know.

Thanks for the great program!

**Comment by dandaman** [comment]
I also encounter this issue - as soon as you move/execute it from a location outside the anaconda path it works (same binary).

**Comment by pjb7687** [comment]
We are not managing the conda package, please contact the package maintainer.
