### ISSUE TITLE
Randomly occurring error with clFinish

### ISSUE THREAD

**Issue by sowmyaiyer** [snugel/cas-offinder#31]
clFinish Failed: -36

There seems to be no pattern or possible cause. If I rerun the same command, it sometimes runs successfully and sometimes returns this error code. Could you please add some details in error reporting to enable better debugging?

**Comment by pjb7687** [comment]
Hi, the error code already gives the most detailed reason why it was failed. The OpenCL error code -36 is  CL_INVALID_COMMAND_QUEUE, which occurs when the command queue is invalid.

https://www.khronos.org/registry/OpenCL/sdk/1.0/docs/man/xhtml/errors.html

Given the symptom randomly occurs, I suggest you check your hardware settings.

**Comment by sowmyaiyer** [comment]
Hi, sorry it still doesn't answer my question. Are you suggesting its a memory issue?
