### ISSUE TITLE
Missing potential off-targets of length less than 23 with gaps? 

### ISSUE THREAD

**Issue by ofiryaish** [snugel/cas-offinder#43]
Hello,

First,  thank you for your amazing work.

Second, I tried to find off-targets with indels, where the cRNA will be of length 23 (it can't have bulges), and the DNA would be of length less than 23 with gaps. For example, In some experimental data, I got for the target (cRNA) "GTCCCTAGTGGCCCCACTGTNGG" the following off-target:
"GTCCTGTGCCCCCACTGTGGG", and the alignment is:

```
        C   A       G
G T C C   T   G T G   C C C C A C T G T N G G
| | | |   |   | | |   | | | | | | | | | | | |
G T C C - T - G T G   C C C C A C T G T G G G
                    C
```

I tried different variations of running cas-offinder, but could found any that generates such examples, even more, simple with off-targets (DNA) of length 22 for example. Do you support those kinds of off-targets?

Moreover, It seems that the tool is providing cRNA with 24 nuclides (when the original size is 23), meaning that it seems like it contains insertion in the guide RNA. How is it possible? The insertion or deletion should be only in the DNA.

Thank you

**Comment by pjb7687** [comment]
Hi @ofiryaish,

At the moment Cas-OFFinder does not support multiple gaps. 

Regarding this:
> Moreover, It seems that the tool is providing cRNA with 24 nuclides (when the original size is 23), meaning that it seems like it > contains insertion in the guide RNA. How is it possible? The insertion or deletion should be only in the DNA.

It is not regarding indels but bulges:
![image](https://user-images.githubusercontent.com/1440536/121740526-7e557b00-cafd-11eb-8ca6-b6cac91fbbbd.png)
