### ISSUE TITLE
Failing to parse input file

### ISSUE THREAD

**Issue by seanExcisionBio** [snugel/cas-offinder#44]
cas-offinder fails to parse the input file even when using the example. 

I receive the following error message: Critical error! The length of target sequences should match with the length of pattern sequence.

Any ideas as to what is causing this or any possible solutions for remedying it?

**Comment by pjb7687** [comment]
Hi, I cannot reproduce this, would be nice if you can upload the input file.

**Comment by seanExcisionBio** [comment]
Hi @pjb7687, I used the input file provided in the documentation: 

/var/chromosomes/human_hg38
NNNNNNNNNNNNNNNNNNNNNRG 2 1
GGCCGACCTGTCGCTGACGCNNN 3 Seq1
CGCCAGCGTCAGCGACAGGTNNN 3 Seq2

For some reason, the script is erroring on a size check for the sequences when the sequences are of the proper identical size.

**Comment by pjb7687** [comment]
Ohhh I see. Actually, this is a 'newer' input file format for Cas-OFFinder > 3.0, and it is currently incompatible with 2.x.
I am still testing 3.x and it won't be released soon. Would you try the input file format mentioned here instead: https://github.com/snugel/cas-offinder/tree/release

And of course, you're always welcome if you want to try out 3.x: https://github.com/snugel/cas-offinder/releases/tag/3.0.0b3
