### ISSUE TITLE
Failure on Mac OSX Catalina

### ISSUE THREAD

**Issue by laruellef** [snugel/cas-offinder#45]
Hi,

Getting :
$ ./cas-offinder ./input.txt C ./output.txt
clBuildProgram Failed: -11
Log from device 0:

System info:
MacBook Pro (15-inch, 2018)
2.2 GHz 6-Core Intel Core i7
GPU:
Radeon Pro 555X 4 GB
Intel UHD Graphics 630 1536 MB
Mac OS: 10.15.7 (19H1323)

Can you help debug this?

Thanks!

Fred

**Comment by pjb7687** [comment]
Hi, I think I can't, it seems to be a general OpenCL issue related to your machine. Please consult Apple to fix it. Thanks!
