### ISSUE TITLE
Looks like a bug with .2bit input

### ISSUE THREAD

**Issue by brownmk** [snugel/cas-offinder#7]
[test.tar.gz](https://github.com/snugel/cas-offinder/files/410013/test.tar.gz)

I have one target sequence in t.fa
I create t.2bit using: faToTwoBit t.fa t.2bit
The query sequence is taken from the target sequence.
If I run: cas-offinder t.fa.in C t.fa.ou, I get the correct output, where it finds an exact match.
ATGGCCAACACTCACCTTCACGG chr5:64476990-64477249  234     ATGGCCAACACTCACCTTCACGG -       0
If I run: cas-offinder t.2bit.in C t.2bit.ou, I get a wrong output, which finds a mismatch that does not exist.
ATGGCCAACACTCACCTTCACGG chr5:64476990-64477249  234     cTGGCCAACACTCACCTTCACGG -       1

Seems like a bug associated with the 2bit input format. Thanks!

**Comment by pjb7687** [comment]
Hello, I fixed the bug in master/development branch.
This only happens when the length of sequence is not divided by 4, then the last 3, 2 or 1 bases would be wrong. Could you test it again? Thank you for your report!

**Comment by brownmk** [comment]
Thank you so much for the speedy fix! Works!
I notice the changes and fixed were still on the development branch, not merged onto the master branch.  Wonder if you consider them mature enough for the master?
We can close the two issue threads, thank you again!

**Comment by pjb7687** [comment]
Nope, the patch is firstly applied to master branch and then merged into develop. We will also release a bug patched release soon.

**Comment by brownmk** [comment]
When I downloaded the master branch yesterday, the code did not take a
sequence file (in the first line of the t.2bit.in file) (it is still
expecting a directory), so it seems earlier changes you made to the
development branch was still in development.

**Comment by pjb7687** [comment]
I released Cas-OFFinder 2.4. All changes were included in the master branch now.
